#!/usr/bin/env python
"""
Plot a functional group, one plot per bond in the database. Plots should appear in a separate window.
"""

from argparse import ArgumentParser

from rascall import database

if __name__ == '__main__':
    PARSER = ArgumentParser(description=__doc__)

    PARSER.add_argument("--fg", nargs="?", help="List Molecules with Functional Group", default="[!#1]C#C[!#1]")

    PARSER.add_argument("--mol", nargs="?", help="List Functional Groups if Molecule", default=None)

    PARSER.add_argument("--mf", nargs="?", help="List Molecules in Family", default="all", choices=["halo","hydro","all"])

    PARSER.add_argument("--fw", nargs="?", help="Molecules in Frequency Window", default=None)

    PARSER.add_argument("--ap", nargs="?", help="List Molecules with Specific Atoms", default=None)

    args = PARSER.parse_args()

    database.plot(args.fg,args.mf)

