#!/usr/bin/env python
"""
Plot a functional group, one plot per bond in the database. Plots should appear in a separate window.
"""

from argparse import ArgumentParser

from rascall import analysis

if __name__ == '__main__':
    PARSER = ArgumentParser(description=__doc__)

    #eg test functional: "[!#1]C#C[!#1]"
    PARSER.add_argument("--fg", nargs="?", help="Plot Molecules with Functional Group", default=None)

    PARSER.add_argument("--mol", nargs="?", help="Plot Single Molecule", default=None)

    PARSER.add_argument("--mf", nargs="?", help="Plot Molecular Family", default="all", choices=["halo","hydro","all"])

    PARSER.add_argument("--fw", nargs="?", help="Molecules in Frequency Window", default=None)

    PARSER.add_argument("--ap", nargs="?", help="Plot Molecules with Specific Atoms", default=None)

    args = PARSER.parse_args()

    analysis.plot(args.fg,args.mf, args.mol)
